using System.Collections.Generic;

namespace SimpleXmlEditor.Localization
{
    public static partial class LocalizationManager
    {
        private static void InitializeTranslationsEn()
        {
            // =========================================================================
            // English (default)
            // =========================================================================
            _translations["en"] = new Dictionary<string, string>
            {
                // === Window titles ===
                ["WindowTitle"] = "Dimension Bridge by Veloxcity & BestFly666",
                ["SettingsTitle"] = "Settings - Dimension Bridge",

                // === Main UI buttons ===
                ["Load"] = "Load",
                ["Save"] = "Save",
                ["Settings"] = "Settings",
                ["Stats"] = "Stats",
                ["ImportDict"] = "Import Dict",
                ["ClearDict"] = "Clear Dict",
                ["BatchReplace"] = "Batch Replace",
                ["Undo"] = "Undo",
                ["QuickSave"] = "Quick Save",
                ["NoExpertDefault"] = "None (Default)",

                // === AI Translation buttons ===
                ["TranslateSelected"] = "Translate Selected",
                ["TranslateAll"] = "Translate All",
                ["Translate"] = "Translate",
                ["Pause"] = "Pause",
                ["Resume"] = "Resume",
                ["Continue"] = "Continue",
                ["Stop"] = "Stop",
                ["ClearCache"] = "Clear Cache",

                // === Section titles ===
                ["AITranslationCenter"] = "AI Translation Center",
                ["TranslationData"] = "Translation Data",
                ["ActivityLog"] = "Activity Log",

                // === Data Grid ===
                ["Select"] = "Select",
                ["Status"] = "Status",
                ["Key"] = "Key",
                ["Original"] = "Original",
                ["Translation"] = "Translation",
                ["Score"] = "Score",

                // === Status bar ===
                ["Ready"] = "Ready",
                ["LoadedEntries"] = "Loaded {0} entries",
                ["MergedTranslations"] = "Merged {0} translations",
                ["SavedEntries"] = "Saved {0} entries to {1}",
                ["NoEntriesForTranslation"] = "No entries need translation",
                ["TranslatingBatch"] = "Translating batch {0}/{1} ({2} entries)...",
                ["WaitingRateLimit"] = "Waiting {0}s before next batch (rate limit optimization)...",
                ["TranslationPaused"] = "Translation paused",
                ["TranslationResumed"] = "Translation resumed",
                ["TranslationStopped"] = "Translation stopped",
                ["TranslationCancelled"] = "Translation cancelled",
                ["NoUntranslatedEntries"] = "No untranslated entries",

                // === Cache/Glossary info ===
                ["CacheInfo"] = "Cache: {0} | Hits: {1} | API: {2}{3}",
                ["Glossary"] = "Glossary",
                ["TipGlossary"] = "Open Glossary Manager",
                ["GlossaryInfo"] = "Glossary: {0} | Hits: {1}",
                ["DictInfo"] = "Dict: {0} | Hits: {1}",
                ["ClearDict"] = "Clear Glossary",
                ["ConfirmClearDict"] = "Clear ALL {0} glossary terms?\nThis cannot be undone!",
                ["LogDictCleared"] = "Glossary cleared",

                // === Glossary Window ===
                ["GlossaryWindowTitle"] = "Glossary Manager",
                ["GlossaryAdd"] = "Add",
                ["GlossaryEdit"] = "Edit",
                ["GlossaryDelete"] = "Delete",
                ["GlossaryImport"] = "Import",
                ["GlossaryExport"] = "Export",
                ["GlossaryMergeProfile"] = "Merge Profile",
                ["GlossaryDetectConflicts"] = "Detect Conflicts",
                ["GlossaryRefresh"] = "Refresh",
                ["GlossaryClose"] = "Close",
                ["GlossaryCancel"] = "Cancel",
                ["GlossarySave"] = "Save",
                ["GlossaryMerge"] = "Merge",
                ["GlossaryFilterAll"] = "All",
                ["GlossaryColEnglish"] = "English (Source)",
                ["GlossaryColChinese"] = "Chinese (Target)",
                ["GlossaryColCategory"] = "Category",
                ["GlossaryColStatus"] = "Status",
                ["GlossaryColTags"] = "Tags",

                // === Blacklist Window ===
                ["Blacklist"] = "Blacklist",
                ["TipBlacklist"] = "Open Blacklist Manager",
                ["LogBlacklistSkipped"] = "Skipped {0} blacklisted entries",
                ["BlacklistWindowTitle"] = "Blacklist Manager",
                ["BlacklistAdd"] = "Add",
                ["BlacklistDelete"] = "Delete",
                ["BlacklistClose"] = "Close",
                ["BlacklistColPrefix"] = "Prefix",
                ["BlacklistCount"] = "{0} rules",
                ["BlacklistExactSection"] = "Original text",
                ["BlacklistColExact"] = "Original Text (exact / ends-with)",
                ["BlacklistHint"] = "Entries whose Key starts with a blacklist prefix, OR whose original text equals or ends with a blacklist entry (case-insensitive), are skipped during translation. E.g. rule UNUSED matches \"Borga:  UNUSED\".",

                // === Export Column Headers (CSV) ===
                ["ColStatus"] = "Status",
                ["ColKey"] = "Key",
                ["ColOriginal"] = "Original",
                ["ColTranslation"] = "Translation",
                ["ColEntryKey"] = "Entry Key",
                ["ColSource"] = "Source Text",
                ["ColTermEnglish"] = "Glossary Term (EN)",
                ["ColExpectedTranslation"] = "Expected Translation",
                ["ColCategory"] = "Category",
                ["ColTranslations"] = "Translations",
                ["ColEntryKeys"] = "Entry Keys",
                ["GlossaryStatus_confirmed"] = "confirmed",
                ["GlossaryStatus_pending"] = "pending",
                ["GlossaryStatus_rejected"] = "rejected",
                ["GlossaryStatusConfirmed"] = "Confirmed",
                ["GlossaryStatusPending"] = "Pending",
                ["GlossaryStatusRejected"] = "Rejected",
                ["GlossaryTermCount"] = "{0} terms total ({1} shown)",
                ["GlossaryStatusSummary"] = "{0} confirmed, {1} pending, {2} rejected",
                ["GlossaryCategoryCount"] = "{0} categories",
                ["GlossarySelectHint"] = "Please select a term first",
                ["GlossaryDeleteConfirm"] = "Delete term \"{0}\"?",
                ["GlossaryImportResult"] = "Import complete: {0} added, {1} updated, {2} skipped",
                ["GlossaryExportResult"] = "Exported {0} terms successfully",
                ["GlossaryNoProfiles"] = "No expert profiles available. Create one in Settings first.",
                ["GlossaryMergeProfileHelp"] = "Select an expert profile to merge its glossary terms:",
                ["GlossarySelectProfileHint"] = "Please select a profile first",
                ["GlossaryMergeResult"] = "Merge complete: {0} terms added, {1} updated",
                ["GlossaryNoConflicts"] = "No terminology conflicts detected. All translations match the glossary!",
                ["GlossaryConflictsTitle"] = "Glossary Conflicts",
                ["GlossaryConflictCount"] = "Detected {0} terminology conflict(s)",
                ["GlossaryExpectedTranslation"] = "Expected",
                ["GlossaryActualTranslation"] = "Actual Translation",
                ["GlossaryEntryKey"] = "Entry Key",
                ["GlossaryExportConflicts"] = "Export CSV",
                ["GlossaryExportConflictsTitle"] = "Export conflict report",
                ["GlossaryExportConflictsDone"] = "Conflict report exported: {0}",
                ["GlossaryRequiredFields"] = "English and Chinese fields are required.",
                ["GlossaryCompare"] = "Compare",

                // === Filter ===
                ["FilterKey"] = "Filter Key",
                ["FilterOriginal"] = "Filter Original",
                ["FilterTranslation"] = "Filter Translation",
                ["ClearFilter"] = "Clear Filter",
                ["FilteredCount"] = "Filtered {0} / {1} entries",

                // === Activity Log ===
                ["RealTime"] = "Real-time",
                ["AutoScroll"] = "Auto-scroll",
                ["ClearLog"] = "Clear Log",
                ["LogConflictStart"] = "🔍 Conflict detection started ({0} entries)...",
                ["LogConflictProgress"] = "🔍 Conflict detection: {0}/{1} entries...",
                ["LogConflictDone"] = "✅ Conflict detection finished: {0} conflict(s) found",

                // === Settings ===
                ["AIConfiguration"] = "AI Configuration",
                ["ConfigureSettings"] = "Configure your AI translation settings",
                ["APIKey"] = "API Key",
                ["EnterAPIKey"] = "Enter your Google Gemini API key from AI Studio",
                ["AIModel"] = "AI Model",
                ["SelectModel"] = "Select an AI model with rate limits and pricing info",
                ["Refresh"] = "Refresh",
                ["Loading"] = "Loading...",
                ["TargetLanguage"] = "Target Language",
                ["SelectTargetLanguage"] = "Select the target language for translation",
                ["ProgramLanguage"] = "Program Language",
                ["SelectProgramLanguage"] = "Select the interface language",
                ["DisableThinking"] = "Disable Thinking Mode (Recommended)",
                ["DisableThinkingHelp"] = "DeepSeek V4 models enable thinking by default. Translation doesn't need reasoning. Disabling can speed up ~7x",
                ["CustomPrompt"] = "Custom Prompt",
                ["CustomPromptHelp"] = "Custom AI translation prompt. Available variables: {LANGUAGE}, {CONTEXT}, {TEXTS}, {EXPERT_CONTEXT}, {GLOSSARY}, {MIXED_SOURCE_NOTE}.",
                ["Reset"] = "Reset",
                ["QuickTips"] = "Quick Tips",
                ["TipAPIKey"] = "Get API key from your chosen AI provider's platform",
                ["TipModels"] = "Each provider offers multiple models to choose from",
                ["TipRateLimits"] = "Rate limits are automatically optimized per model",
                ["TipCache"] = "Translation cache reduces API costs",
                ["TipLanguages"] = "30 target languages supported",
                ["SaveApply"] = "Save & Apply",
                ["Cancel"] = "Cancel",
                ["NewProfile"] = "New Profile",
                ["EditProfile"] = "Edit: {0}",

                // === MessageBox titles ===
                ["MsgError"] = "Error",
                ["MsgSuccess"] = "Success",
                ["MsgConfirm"] = "Confirm",
                ["MsgWarning"] = "Warning",
                ["MsgTip"] = "Tip",

                // === MessageBox messages ===
                ["EnterAPIKeyFirst"] = "Please enter an API Key",
                ["SelectModelFirst"] = "Please select a model",
                ["EnterProfileName"] = "Please enter a profile name.",
                ["SelectEntriesFirst"] = "Please select entries to translate first",
                ["SearchTermEmpty"] = "Search term cannot be empty",
                ["NoModelsFound"] = "No models found. Please check your API key.",
                ["ModelsFoundSuccess"] = "Found {0} models with rate limit information",
                ["ErrorFetchingModels"] = "Error fetching models: {0}",
                ["GeminiKeyFormatWarning"] = "The Gemini API key starts with 'sk-', which is typical of other providers (e.g. DeepSeek). Google Gemini keys usually start with 'AIza'. Please verify the key is correct.",
                ["ConfigLoadError"] = "Config load error: {0}",
                ["ConfigSaveError"] = "Config save error: {0}",
                ["ErrorLoadingXml"] = "Error loading XML: {0}",
                ["UnsupportedXmlFormat"] = "Unrecognized XML format (root element: {0}). Supported: LocalisationData / Excel Spreadsheet.",
                ["ErrorSavingXml"] = "Error saving XML: {0}",
                ["TranslationError"] = "Translation error: {0}",
                ["ImportError"] = "Import error: {0}",
                ["CacheSaveError"] = "Cache save failed: {0}",

                // === Confirm dialogs ===
                ["ConfirmTranslate"] = "Will translate {0} entries. This may take some time.",
                ["ConfirmClearCache"] = "Clear {0} cached translations?",
                ["ConfirmClearDict"] = "Clear {0} dictionary entries? This does not affect completed translations.",
                ["ConfirmDeleteProfile"] = "Are you sure you want to delete profile \"{0}\"? This cannot be undone.",
                ["ConfirmBatchReplace"] = "Replace complete! Modified {0} translations.\n\nClick Undo to revert.",

                // === Operation results ===
                ["TranslationComplete"] = "Translation complete: {0} success, {1} failed",
                ["TranslationStoppedResult"] = "Translation stopped: {0} success, {1} failed",
                ["NoEntriesNeedTranslation"] = "No entries need translation",
                ["ImportCsvDone"] = "Import complete!\nAdded: {0}\nUpdated: {1}\nSkipped: {2}",
                ["ImportJsonDone"] = "Import complete!\nAdded: {0}\nUpdated: {1}",
                ["BatchReplaceDone"] = "Batch replace complete - {0} replacements",
                ["UndoComplete"] = "Undo complete! Restored {0} translations",
                ["NothingToUndo"] = "Nothing to undo",
                ["ModelsFetchSuccess"] = "Found {0} models with rate limits, {1} with pricing info, {2} with limits",

                // === File dialog titles ===
                ["SelectXmlFile"] = "Select XML Localization File",
                ["SaveXmlFile"] = "Save XML Localization File",
                ["ImportDictTitle"] = "Import Translation Dictionary",

                // === Input dialog labels ===
                ["BatchReplaceDialogTitle"] = "Batch Replace",
                ["SearchTermLabel"] = "Search Term",
                ["ReplaceWithLabel"] = "Replace With",

                // === Log messages ===
                ["LogAutoLoad"] = "Auto-loaded last file: {0}",
                ["LogStarted"] = "Program started",
                ["LogConfigLoaded"] = "Config loaded",
                ["LogConfigSaved"] = "Config saved",
                ["LogCacheLoaded"] = "Cache loaded - {0} entries",
                ["LogFileNotFound"] = "{0} not found",
                ["LogXmlLoaded"] = "XML loaded - {0} entries",
                ["LogTranslationMerged"] = "Translation merged - {0}/{1} entries matched",
                ["LogXmlSaved"] = "XML saved to {0} - {1} entries",
                ["LogBatchCost"] = "Batch translation cost: ${0} ({1} entries, input: {2} chars, output: {3} chars)",
                ["LogSingleCost"] = "Translation cost: ${0} (input: {1} chars, output: {2} chars)",
                ["LogParseError"] = "Batch parse error: {0}",
                ["LogRateLimit429"] = "Rate limit (HTTP 429), waiting {0}s before retry {1}/{2}",
                ["LogRateLimitExhausted"] = "Translation failed after {0} retries: rate limit",
                ["LogRetryError"] = "Error, waiting {0}s before retry: {1}",
                ["LogTranslationFailed"] = "Translation error after {0} retries: {1}",
                ["LogModelInfo"] = "{0}: {1} (input: {2}, output: {3} tokens)",
                ["LogRateLimitEstimate"] = "{0} estimated rate limit: {1}/min, {2}/day",
                ["LogModelsFound"] = "Found {0} models, {1} with pricing, {2} with limits",
                ["LogDeepSeekModels"] = "Static model list loaded: {0} models",
                ["LogRateLimitReached"] = "Rate limit reached ({0}/min), waiting {1}s",
                ["LogOptimalDelay"] = "{0} optimal delay: {1}s ({2} remaining requests/min)",
                ["LogGenericPricing"] = "Using generic pricing for {0} - refresh models for accurate pricing",
                ["LogSettingsUpdated"] = "Settings updated - Provider: {0}, Model: {1}, Language: {2}, Expert: {3}",
                ["LogNoTranslationNeeded"] = "No entries need translation",
                ["LogBatchStart"] = "Starting batch translation: {0} entries, {1} batches{2}",
                ["LogBatchModel"] = "Model: {0} (rate limit options checked)",
                ["LogBatchCancelled"] = "Translation cancelled at batch {0}/{1}",
                ["LogBatchProgress"] = "Processing batch {0}/{1}: {2} entries",
                ["LogBatchFails"] = "Failed {0} entries: {1}",
                ["LogBatchRetryHalve"] = "Batch of {0} failed (likely output length or timeout), auto-splitting and retrying...",
                ["LogBatchDone"] = "Batch {0}/{1} complete: {2} success, {3} failed | Progress saved",
                ["LogBatchElapsed"] = "Batch {0}/{1} took {2}s ({3} entries)",
                ["LogCacheSaved"] = "Cache saved",
                ["LogTranslationDone"] = "{0}",
                ["LogTipHeader"] = "Tips to reduce failures:",
                ["LogTip1"] = "  - Wait a few seconds and retry",
                ["LogTip2"] = "  - Reduce batch size in code (currently 50)",
                ["LogTip3"] = "  - Decrease number of concurrent threads",
                ["LogEfficiency"] = "Translation efficiency: {0}% ({1}/{2})",
                ["LogBatchEfficiency"] = "Batch efficiency: {0} API calls instead of {1} (saved {2} calls)",
                ["LogRateLimitStatus"] = "Rate limit status: {0}/{1} used this minute",
                ["LogTranslationCancelled"] = "Translation cancelled",
                ["LogTranslationAlreadyRunning"] = "Translation is already running. Please wait for the current task to finish.",
                ["LogProgressSaveError"] = "Progress save failed: {0}",
                ["LogCrashRecovery"] = "Restored {0} translations from crash recovery file",
                ["LogRecoveryError"] = "Recovery file error: {0}",
                ["LogProgressDeleteError"] = "Progress file delete failed: {0}",
                ["LogCacheCleared"] = "Cache cleared",
                ["LogCsvImported"] = "CSV dictionary imported - Added {0}, Updated {1}",
                ["LogJsonImported"] = "JSON dictionary imported - Added {0}, Updated {1}",
                ["LogDictApplied"] = "Dictionary matched {0} existing entries",
                ["LogDictCleared"] = "Dictionary cleared",
                ["LogPluginLoaded"] = "Loaded plugin DLL: {0}",
                ["LogPluginLoadFailed"] = "Failed to load plugin {0}: {1}",
                ["LogPluginFormatDiscovered"] = "Discovered format plugin: {0} ({1})",
                ["LogPluginFormatFailed"] = "Failed to instantiate format plugin {0}: {1}",
                ["LogPluginPostDiscovered"] = "Discovered post-process plugin: {0}",
                ["LogPluginPostFailed"] = "Failed to instantiate post-process plugin {0}: {1}",
                ["LogVotingFailed"] = "⚠ Voting failed: {0}",
                ["LogCandidateGenFailed"] = "⚠ Candidate generation failed: {0}",
                ["LogEvalParseFallback"] = "⚠ Batch evaluation parse failed, falling back to per-entry",
                ["LogPerEntryEvalFailed"] = "⚠ Per-entry evaluation failed for {0}: {1}",
                ["LogEvalChunkFailed"] = "⚠ Batch evaluation chunk failed: {0}",
                ["LogVotingParseFallback"] = "⚠ Batch voting parse failed, falling back to per-entry",
                ["LogPerEntryVotingFailed"] = "⚠ Per-entry voting failed for {0}: {1}",
                ["LogVotingChunkFailed"] = "⚠ Batch voting chunk failed: {0}",
                ["LogAgentScored"] = "🗳 {0} scored {1:F1}/10 for: {2}",
                ["LogVotingRegexFallback"] = "⚠ Batch voting parse failed, trying regex fallback",
                ["LogRateLimitedRetry"] = "Rate limited (HTTP 429), retry {0}/{1} after {2}s",
                ["LogScoreCacheLoaded"] = "Score cache loaded - {0} entries",
                ["LogApiKeyEncryptFailed"] = "API key encryption failed: {0}",
                ["LogApiKeyPlaintextWarning"] = "WARNING: DPAPI encryption failed. The API key will NOT be saved to disk (session only).",
                ["LogApiKeyDecryptFailed"] = "API key decryption failed: {0}",
                ["LogMigratedLegacyKey"] = "Migrated legacy plaintext API key to encrypted storage",
                ["LogMigrationFailed"] = "Migration failed: {0}",
                ["LogScoreCacheWriteError"] = "Score cache write error: {0}",
                ["LogScoresRestored"] = "Restored {0} scores from cache",
                ["LogApiKeyNotSet"] = "API Key not set",
                ["LogModelNotSelected"] = "Model not selected",
                ["LogBatchReplace"] = "Batch replace complete - {0} replacements",
                ["LogUndo"] = "Undo applied - previous operation reverted",
                ["LogCacheUpdated"] = "Cache updated - {0} entries",
                ["LogCacheWriteError"] = "Cache write error: {0}",
                ["LogCleared"] = "Log cleared",
                ["LogPaused"] = "Translation paused",
                ["LogResumed"] = "Translation resumed",
                ["LogStopped"] = "Translation stopped",
                ["LogExpertProfile"] = "Expert config: {0}",
                ["LogAutoRefreshModels"] = "Auto-refreshing available models...",
                ["LogAutoModelsLoaded"] = "Auto-loaded {0} models",
                ["LogAutoModelSelected"] = "Auto-selected model: {0}",
                ["LogClearedTranslation"] = "Cleared {0} translations",
                ["StatusStoppedResult"] = "Translation stopped: {0} success, {1} failed",
                ["StatusBatchComplete"] = "Batch translation complete: {0} success, {1} failed",

                // === Filter bar labels ===
                ["FilterLabel"] = "Filter",
                ["FilterKeyColumn"] = "Key",
                ["FilterOriginalColumn"] = "Original",
                ["FilterTranslationColumn"] = "Translation",
                ["FilterClear"] = "Clear",
                ["TotalCount"] = "{0} total entries",

                // === Settings window ===
                ["SettingsSubtitle"] = "Configure AI translation and expert profiles",
                ["GeneralSettings"] = "General Settings",
                ["ExpertProfiles"] = "Expert Profiles",
                ["AiProviderLabel"] = "AI Provider",
                ["SelectAiProvider"] = "Select AI translation service provider",
                ["EnterYourApiKey"] = "Enter your API key",
                ["SavedProfiles"] = "Saved Profiles",
                ["AddProfile"] = "Add Profile",
                ["ProfileEditTitle"] = "Edit Profile",
                ["ProfileNameLabel"] = "Profile Name",
                ["ProfileDescLabel"] = "Description",
                ["ProfileContextLabel"] = "Context & Thinking Instructions",
                ["ProfileContextHelp"] = "Tell AI how to understand this domain. Use {LANGUAGE} for target language.",
                ["ProfileGlossaryLabel"] = "Glossary",
                ["ProfileGlossaryHelp"] = "One term per line. Format: source = translated term",
                ["SaveProfileBtn"] = "Save",
                ["ExpertSystemTitle"] = "Expert Profile System",
                ["ExpertSystemDesc"] = "Expert profiles let you define domain-specific knowledge. Each contains thinking instructions and a terminology glossary. When activated, this knowledge is injected into every translation request for maximum accuracy.",
                ["BatchLabel"] = "Batch",
                ["GlossaryLimitLabel"] = "Terms",
                ["AppName"] = "Dimension Bridge",

                // === Find bar ===
                ["FindLabel"] = "Find:",
                ["FindNoMatch"] = "No matches",
                ["FindMatchCount"] = "{0} matches",
                ["FindPrevious"] = "Prev",
                ["FindNext"] = "Next",

                // === Context menu ===
                ["CtxCopyKey"] = "Copy Key",
                ["CtxCopyOriginal"] = "Copy Original",
                ["CtxCopyTranslation"] = "Copy Translation",
                ["CtxClearTranslation"] = "Clear Translation",
                ["CtxTranslateSelected"] = "Translate Selected",
                ["CtxEvaluate"] = "AI Evaluate",
                ["CtxVote"] = "Agent Vote",
                ["CtxSelectAll"] = "Select All",
                ["CtxSelectNone"] = "Select None",
                ["CtxInvertSelection"] = "Invert Selection",
                ["SelectingColumn"] = "Selecting column",
                ["SelectingAll"] = "Selecting all",
                ["InvertingSelection"] = "Inverting selection",
                ["SelectedCount"] = "Selected",

                // === Prompt messages ===
                ["MsgPrompt"] = "Prompt",
                ["SelectFirstToTranslate"] = "Please select entries to translate first",
                ["EnterApiKeyFirstMsg"] = "Please enter an API key first",

                // === Stats dialog ===
                ["StatsTitle"] = "Statistics",
                ["StatsInfo"] = "Total: {0}\nTranslated: {1}\nUntranslated: {2}\nProgress: {3:F1}%\n\nDictionary: {4} entries | Hits: {5}\nCache: {6} | Hits: {7}\nAPI calls: {8}",

                // === ToolTips ===
                ["TipSaveAs"] = "Save As...",
                ["TipQuickSave"] = "Quick Save (Ctrl+S) - Save to currently opened file",
                ["TipImportDict"] = "Import CSV/JSON dictionary",
                ["TipBatchReplace"] = "Batch search and replace translations",
                ["TipUndo"] = "Undo last batch replace",
                ["TipFilterKey"] = "Filter by Key (e.g. TEXT_TOOLTIP_...)",
                ["TipFilterOriginal"] = "Filter by original text",
                ["TipFilterTranslation"] = "Filter by translation text",

                // === Dialogs ===
                ["OK"] = "OK",
                ["FileTypeTitle"] = "Select File Type",
                ["FileTypePrompt"] = "Is this file source or translation?",
                ["SourceFile"] = "Source",
                ["TranslationFile"] = "Translation",

                // === Custom prompt help ===
                ["CustomPromptSyntaxHelp"] = "Customize the AI translation prompt. Available variables: {LANGUAGE} (target language), {CONTEXT} (content type), {TEXTS} (data to translate), {EXPERT_CONTEXT} (expert profile knowledge, auto-replaced), {GLOSSARY} (glossary terms, auto-injected), {MIXED_SOURCE_NOTE} (correction directive for mixed batches).",

                // === Quick tips ===
                ["QuickTipsTitle"] = "Quick Tips",
                ["QuickTipsContent"] = "• Supports 8 AI providers (Google, DeepSeek, Doubao, Qianwen, Zhipu, Moonshot, Wenxin, Xunfei)\n• Each provider offers multiple models to choose from\n• Batch translation with automatic concurrency\n• Glossary auto-injection for consistent translations\n• Translation cache reduces API costs\n• AI evaluation and multi-agent voting for quality\n• 30 target languages supported\n• Expert profiles inject domain knowledge for specialized translation",

                // === Misc labels ===
                ["CostLabel"] = "Cost",
                ["LoadModelRefreshHint"] = "(click Refresh to load full list)",

                // === AI Evaluation & Voting ===
                ["EvaluateBtn"] = "Evaluate",
                ["VoteBtn"] = "Agent Vote",
                ["EvaluateToolTip"] = "AI quality evaluation (0-10 score)",
                ["VoteToolTip"] = "Multi-agent voting for best translation",
                ["EvalEvaluating"] = "Evaluating...",
                ["EvalVoting"] = "Voting...",
                ["EvalFailed"] = "Evaluation failed",
                ["VoteFailed"] = "Voting failed",
                ["Best"] = "Best",
                ["NoTranslatedToEvaluate"] = "No translated entries to evaluate",
                ["NoTranslatedToVote"] = "No translated entries for voting",
                ["LogEvaluating"] = "Evaluating: {0}",
                ["LogVoting"] = "Agent voting: {0}",
                ["LogEvalResult"] = "{0}: {1:F1}/10 — {2}",
                ["LogEvalSuggestion"] = "Suggestion: {0}",
                ["LogVoteConsensus"] = "{0}",
                ["LogVoteAgentDetail"] = "  {0}: {1:F1}/10 — {2}",
                ["EvalScoreToolTip"] = "Score: {0:F1}/10\nExplanation: {1}\nSuggestion: {2}",
                ["VoteResultToolTip"] = "Average Score: {0:F1}/10\nConsensus: {1}\nAgents: {2} votes",

                // === Target language names ===
                ["Lang_Turkish"] = "Turkish",
                ["Lang_Spanish"] = "Spanish",
                ["Lang_French"] = "French",
                ["Lang_German"] = "German",
                ["Lang_Italian"] = "Italian",
                ["Lang_Portuguese"] = "Portuguese",
                ["Lang_Russian"] = "Russian",
                ["Lang_Japanese"] = "Japanese",
                ["Lang_Korean"] = "Korean",
                ["Lang_Chinese_Simplified"] = "Chinese (Simplified)",
                ["Lang_Chinese_Traditional"] = "Chinese (Traditional)",
                ["Lang_Arabic"] = "Arabic",
                ["Lang_Hindi"] = "Hindi",
                ["Lang_Dutch"] = "Dutch",
                ["Lang_Swedish"] = "Swedish",
                ["Lang_Norwegian"] = "Norwegian",
                ["Lang_Danish"] = "Danish",
                ["Lang_Finnish"] = "Finnish",
                ["Lang_Polish"] = "Polish",
                ["Lang_Czech"] = "Czech",
                ["Lang_Hungarian"] = "Hungarian",
                ["Lang_Romanian"] = "Romanian",
                ["Lang_Greek"] = "Greek",
                ["Lang_Bulgarian"] = "Bulgarian",
                ["Lang_Ukrainian"] = "Ukrainian",
                ["Lang_Thai"] = "Thai",
                ["Lang_Vietnamese"] = "Vietnamese",
                ["Lang_Indonesian"] = "Indonesian",
                ["Lang_Hebrew"] = "Hebrew",
                ["Lang_Persian"] = "Persian",

                // === Review & Export ===
                ["ExportReview"] = "Export Review",
                ["ReviewReport"] = "Review Report",
                ["ReviewStatusReviewed"] = "Reviewed",
                ["ReviewStatusNeedsFix"] = "Needs Fix",
                ["ReviewStatusNotReviewed"] = "Not Reviewed",
                ["MarkedEntriesAsStatus"] = "Marked {0} entries as {1}",
                ["ExportReviewLog"] = "Review report exported: {0} entries | ✅ {1} | 🔧 {2} | 📝 {3}",
                ["ExportReviewMsg"] = "Exported {0} entries.\nReviewed: {1}\nNeeds Fix: {2}\nNot Reviewed: {3}",

                // === Evaluation Window ===
                ["EvaluationTitle"] = "Translation Quality Evaluation",
                ["EvalScoreDist"] = "Score Distribution: ",
                ["EvalHighCount"] = "Excellent (8-10): {0}",
                ["EvalMidCount"] = "Good (5-7): {0}",
                ["EvalLowCount"] = "Poor (0-4): {0}",
                ["EvalAvgScore"] = "Average: {0:F1}/10",
                ["EvalEvaluated"] = "Evaluated {0} entries",
                ["EvalNA"] = "N/A",
                ["EvalApplySuggestion"] = "Apply Suggestion",
                ["EvalMarkLowScores"] = "Mark Low Scores",
                ["EvalClose"] = "Close",
                ["EvalMarkComplete"] = "Mark Complete",
                ["EvalMarkedEntries"] = "Marked {0} entries for review.",
                ["EvalAppliedSuggestion"] = "Applied suggestion for: {0}",
                ["EvalMarkAsLow"] = "Mark as low: {0} (Score: {1:F1})",

                // === Batch Evaluation & Voting ===
                ["LogBatchEvaluating"] = "Evaluating {0} translations...",
                ["EvalBatchProgress"] = "Evaluating {0}...",
                ["EvalNoResults"] = "No results",
                ["EvalBatchSummary"] = "Avg: {0:F1} | High: {1} | Low: {2}",
                ["LogBatchEvalComplete"] = "Batch evaluation complete: {0} entries, Avg: {1:F1}, High: {2}, Low: {3}",
                ["LogScoreUpdated"] = "Updated {0} scores to the table (click Score column header to sort)",
                ["LogBatchVoting"] = "Multi-agent voting for {0} entries...",
                ["VoteBatchProgress"] = "Voting {0}...",
                ["VoteBatchResult"] = "{0} voted | Best: {1}",
                ["LogBatchVoteComplete"] = "Batch voting complete: {0} entries, {1} entries rated best",
                ["LogAppliedSuggestion"] = "Applied suggestion for: {0}",
                ["VoteAppliedBest"] = "Voting complete: applied best translation to {0} entries",
                ["LogGeneratingCandidate"] = "Generating candidates [{0}/{1}] for: {2}",
                ["VoteCandidateProgress"] = "Generating candidates [{0}/{1}]...",
                ["LogVotingStart"] = "Starting multi-agent voting for {0} entries...",
                ["VoteVotingProgress"] = "Voting on {0} entries...",
                ["VoteBatchResultDetail"] = "{0} voted | Best: {1} | Review: {2}",
                ["VoteBestTranslation"] = "Best translation",
                ["VoteApplyPrompt"] = "Apply best translation for \"{0}\"?\n\n{1}",
                ["VoteApplyTitle"] = "Apply Best Translation",
                ["VoteApplied"] = "Best translation applied for {0}",
                ["VoteNeedsReview"] = "{0} entries need manual review",
                ["VotingReviewTitle"] = "Review Voting Candidates",
                ["VotingReviewHint"] = "{0} entries need review — choose which translation to use for each",
                ["VotingKeepCurrent"] = "(Keep current translation)",
                ["VotingCandidateFormat"] = "Candidate {0} (avg {1:F1}/10)",
                ["VotingApplySelected"] = "Apply Selected",
                ["VotingCancel"] = "Cancel",

                // === Glossary ===
                ["GlossaryShare"] = "Share",
                ["GlossaryShareTitle"] = "Share Glossary for Community",
                ["GlossaryShareResult"] = "Shared {0} terms for community use.",
                ["GlossaryImportTitle"] = "Import Glossary",
                ["GlossaryExportTitle"] = "Export Glossary",
                ["MsgError"] = "Error",

                // === File dialog ===
                ["FileFilterAllSupported"] = "All Supported Files",
                ["FileFilterXml"] = "XML Files",
                ["FileFilterPo"] = "PO Files",
                ["FileFilterJson"] = "JSON Files",
                ["FileFilterAll"] = "All Files",
                ["FileFilterCsv"] = "CSV Files",

                // === Save/Load with plugins ===
                ["LogSavedFile"] = "Saved {0} entries as {1}: {2}",
                ["LogLoadedFile"] = "Loaded {0} entries ({1}): {2}",
                ["StatusSavedPlugin"] = "Saved {0} entries ({1})",

                // === Term Edit Dialog ===
                ["TermAddTitle"] = "Add Term",
                ["TermEditTitle"] = "Edit Term",

                // === Misc dialogs ===
                ["GlossaryShareResultTitle"] = "Shared",
                ["ExportFailed"] = "Export failed: {0}",

                // === Progress display ===
                ["ProgressDisplay"] = "{0:F1}% ({1}/{2})",
                ["SpeedDisplay"] = "{0:F1}/s",
                ["EtaDisplay"] = "{0}",
                ["CostDisplay"] = "¥{0:F2}",
                ["FindPosition"] = "{0} / {1}",
                ["LogFileClosed"] = "File closed",
                ["NoFileLoaded"] = "No file loaded",

                // === Menu ===
                ["MenuFile"] = "File",
                ["MenuEdit"] = "Edit",
                ["MenuView"] = "View",
                ["MenuTranslate"] = "Translate",
                ["MenuQuality"] = "Quality",
                ["MenuTools"] = "Tools",
                ["MenuHelp"] = "Help",
                ["MenuOpen"] = "Open...",
                ["MenuSave"] = "Save",
                ["MenuSaveAs"] = "Save As...",
                ["MenuExport"] = "Export",
                ["MenuExit"] = "Exit",
                ["MenuUndo"] = "Undo",
                ["MenuFind"] = "Find...",
                ["MenuReplace"] = "Replace...",
                ["MenuDarkMode"] = "Dark Mode",
                ["MenuLightMode"] = "Light Mode",
                ["MenuShowFilter"] = "Show Filter Bar",
                ["MenuShowLog"] = "Show Activity Log",
                ["MenuSmartPre"] = "Smart Pre-translate",
                ["MenuConsistency"] = "Consistency Scan",
                ["MenuShortcuts"] = "Keyboard Shortcuts",
                ["MenuAbout"] = "About",

                // === Untranslated filter ===
                ["ShowUntranslatedOnly"] = "Show Untranslated Only",
                ["ShowAll"] = "Show All",
                ["HideBlacklisted"] = "Hide Blacklist",

                // === Smart Pre-translate ===
                ["PreTranslate"] = "Smart Pre-translate",
                ["PreTranslateTip"] = "Fill translations from glossary and cache without API calls",
                ["PreTranslateResult"] = "{0} entries pre-translated (glossary: {1}, cache: {2})",
                ["LogPreTranslate"] = "Smart pre-translate: {0} entries filled (glossary: {1}, cache: {2})",

                // === Consistency Scan ===
                ["ConsistencyScan"] = "Consistency Scan",
                ["ConsistencyScanTitle"] = "Consistency Check Results",
                ["ConsistencyScanning"] = "Scanning for inconsistencies...",
                ["ConsistencyNoIssues"] = "No consistency issues found.",
                ["ConsistencyIssueDesc"] = "{0} → translated as \"{1}\" and \"{2}\"",
                ["LogConsistencyScan"] = "Consistency scan: {0} issues found in {1} entries",
                ["ConsistencyExportPrompt"] = "Found {0} consistency issues. Export a report for reference?",
                ["ConsistencyExported"] = "Consistency report exported: {0}",

                // === Context-aware Translation ===
                ["ContextAware"] = "Context-aware",
                ["LogContextAware"] = "Context-aware mode: analyzing {0} neighboring entries for {1}",

                // === Fuzzy Matching ===
                ["FuzzyMatch"] = "Fuzzy Match",
                ["FuzzyMatchResult"] = "{0} fuzzy matches found for \"{1}\"",

                // === Multi-file ===
                ["ProjectFiles"] = "Project Files",
                ["CloseFile"] = "Close File",
                ["CloseTab"] = "Close",

                // === About ===
                ["AboutTitle"] = "About Dimension Bridge",
                ["AboutText"] = "Dimension Bridge v1.0\n\nAI-powered game localization tool.\nSupports XML, CSV, JSON, INI, YAML, RESX, PO, TXT, Android.\n\n8 AI providers, 30+ languages.",

                // === Shortcuts ===
                ["ShortcutsTitle"] = "Keyboard Shortcuts",
                ["ShortcutsText"] = "Ctrl+O   Open File\nCtrl+S   Quick Save\nCtrl+Z   Undo\nCtrl+F   Find\nF5       AI Evaluate\nF6       Agent Vote\nCtrl+T   Translate Selected\nCtrl+Shift+T  Translate All\nEscape   Clear Filters",

                // === Evaluation Model Settings ===
                ["EvalModelTab"] = "Evaluation Model",
                ["EvalModelConfig"] = "Evaluation Model Configuration",
                ["EvalModelDesc"] = "Configure a separate AI model for evaluation and voting to break same-source bias. Leave empty to use the translation model.",
                ["EvalAiProviderLabel"] = "Evaluation AI Provider",
                ["EvalApiKeyLabel"] = "Evaluation API Key",
                ["EvalApiKeyPlaceholder"] = "Enter evaluation model API key (empty = use translation key)",
                ["EvalModelNameLabel"] = "Evaluation Model Name",
                ["EvalModelPlaceholder"] = "Enter model name, e.g. deepseek-chat, glm-4-flash",
                ["EvalUseTranslationModel"] = "(Use Translation Model)",
                ["EvalRefreshModels"] = "Refresh Models",
                ["EvalAddModel"] = "Add Model",
                ["EvalAddedModels"] = "Configured Evaluation Models",
                ["EvalModelListEmpty"] = "(No models added — voting will use the translation model)",
                ["EvalSelectModelFirst"] = "Please select a model first",
                ["EvalModelAdded"] = "Model added: {0}",
                ["EvalUseSameKeyHint"] = "Models of the same provider can share one API Key. Voting calls all configured models.",
            };
        }
    }
}
