using System.Collections.Generic;

namespace SimpleXmlEditor.Localization
{
    public static partial class LocalizationManager
    {
        private static void InitializeTranslationsZh()
        {
            // =========================================================================
            // Chinese (Simplified)
            // =========================================================================
            _translations["zh"] = new Dictionary<string, string>
            {
                // === Window titles ===
                ["WindowTitle"] = "次元译桥 by Veloxcity & BestFly666",
                ["SettingsTitle"] = "设置 - 次元译桥",

                // === Main UI buttons ===
                ["Load"] = "加载",
                ["Save"] = "保存",
                ["Settings"] = "设置",
                ["Stats"] = "统计",
                ["ImportDict"] = "导入对照表",
                ["ClearDict"] = "清除对照表",
                ["BatchReplace"] = "批量替换",
                ["Undo"] = "撤销",
                ["QuickSave"] = "快速保存",
                ["NoExpertDefault"] = "无专家（默认）",

                // === AI Translation buttons ===
                ["TranslateSelected"] = "翻译选中",
                ["TranslateAll"] = "全部翻译",
                ["Translate"] = "翻译",
                ["Pause"] = "暂停",
                ["Resume"] = "继续",
                ["Continue"] = "继续",
                ["Stop"] = "停止",
                ["ClearCache"] = "清除缓存",

                // === Section titles ===
                ["AITranslationCenter"] = "AI 翻译中心",
                ["TranslationData"] = "翻译数据",
                ["ActivityLog"] = "活动日志",

                // === Data Grid ===
                ["Select"] = "选择",
                ["Status"] = "状态",
                ["Key"] = "键",
                ["Original"] = "原文",
                ["Translation"] = "译文",
                ["Score"] = "评分",

                // === Status bar ===
                ["Ready"] = "就绪",
                ["LoadedEntries"] = "已加载 {0} 条记录",
                ["MergedTranslations"] = "已合并 {0} 条译文",
                ["SavedEntries"] = "已保存 {0} 条记录至 {1}",
                ["NoEntriesForTranslation"] = "没有需要翻译的条目",
                ["TranslatingBatch"] = "正在翻译第 {0}/{1} 批 ({2} 条)...",
                ["WaitingRateLimit"] = "等待 {0} 秒后开始下一批（速率限制优化）...",
                ["TranslationPaused"] = "翻译已暂停",
                ["TranslationResumed"] = "翻译已继续",
                ["TranslationStopped"] = "翻译已停止",
                ["TranslationCancelled"] = "翻译已取消",
                ["NoUntranslatedEntries"] = "没有未翻译的条目",

                // === Cache/Glossary info ===
                ["CacheInfo"] = "缓存: {0} | 命中: {1} | API: {2}{3}",
                ["Glossary"] = "术语表",
                ["TipGlossary"] = "打开术语管理器",
                ["GlossaryInfo"] = "术语表: {0} | 命中: {1}",
                ["DictInfo"] = "对照表: {0} | 命中: {1}",
                ["ClearDict"] = "清除术语表",
                ["ConfirmClearDict"] = "确定要清除全部 {0} 个术语吗？\n此操作不可撤销！",
                ["LogDictCleared"] = "术语表已清除",

                // === Glossary Window ===
                ["GlossaryWindowTitle"] = "术语管理器",
                ["GlossaryAdd"] = "新增",
                ["GlossaryEdit"] = "编辑",
                ["GlossaryDelete"] = "删除",
                ["GlossaryImport"] = "导入",
                ["GlossaryExport"] = "导出",
                ["GlossaryMergeProfile"] = "合并专家配置",
                ["GlossaryDetectConflicts"] = "冲突检测",
                ["GlossaryRefresh"] = "刷新",
                ["GlossaryClose"] = "关闭",
                ["GlossaryCancel"] = "取消",
                ["GlossarySave"] = "保存",
                ["GlossaryMerge"] = "合并",
                ["GlossaryFilterAll"] = "全部",
                ["GlossaryColEnglish"] = "英文（源）",
                ["GlossaryColChinese"] = "中文（目标）",
                ["GlossaryColCategory"] = "分类",
                ["GlossaryColStatus"] = "状态",
                ["GlossaryColTags"] = "标签",

                // === Blacklist Window ===
                ["Blacklist"] = "黑名单",
                ["TipBlacklist"] = "打开黑名单管理器",
                ["LogBlacklistSkipped"] = "已跳过 {0} 条黑名单条目",
                ["BlacklistWindowTitle"] = "黑名单管理",
                ["BlacklistAdd"] = "添加",
                ["BlacklistDelete"] = "删除",
                ["BlacklistClose"] = "关闭",
                ["BlacklistColPrefix"] = "前缀",
                ["BlacklistCount"] = "{0} 条规则",
                ["BlacklistExactSection"] = "原文匹配",
                ["BlacklistColExact"] = "原文（精确或结尾匹配）",
                ["BlacklistHint"] = "Key 以黑名单前缀开头、或原文与黑名单文本完全一致 / 以其结尾（忽略大小写）的条目，将在翻译时被跳过。例如规则 UNUSED 可命中 \"Borga:  UNUSED\"。",

                // === Export Column Headers (CSV) ===
                ["ColStatus"] = "状态",
                ["ColKey"] = "Key",
                ["ColOriginal"] = "原文",
                ["ColTranslation"] = "译文",
                ["ColEntryKey"] = "条目 Key",
                ["ColSource"] = "原文",
                ["ColTermEnglish"] = "术语（英文）",
                ["ColExpectedTranslation"] = "应译为",
                ["ColCategory"] = "分类",
                ["ColTranslations"] = "不一致译文",
                ["ColEntryKeys"] = "条目 Key",
                ["GlossaryStatus_confirmed"] = "已确认",
                ["GlossaryStatus_pending"] = "待审核",
                ["GlossaryStatus_rejected"] = "已拒绝",
                ["GlossaryStatusConfirmed"] = "已确认",
                ["GlossaryStatusPending"] = "待审核",
                ["GlossaryStatusRejected"] = "已拒绝",
                ["GlossaryTermCount"] = "{0} 个术语（显示 {1}）",
                ["GlossaryStatusSummary"] = "{0} 已确认, {1} 待审核, {2} 已拒绝",
                ["GlossaryCategoryCount"] = "{0} 个分类",
                ["GlossarySelectHint"] = "请先选择一个术语",
                ["GlossaryDeleteConfirm"] = "确定要删除术语 \"{0}\" 吗？",
                ["GlossaryImportResult"] = "导入完成: 新增 {0}, 更新 {1}, 跳过 {2}",
                ["GlossaryExportResult"] = "成功导出 {0} 个术语",
                ["GlossaryNoProfiles"] = "没有可用的专家配置。请先在设置中创建。",
                ["GlossaryMergeProfileHelp"] = "选择一个要合并术语的专家配置:",
                ["GlossarySelectProfileHint"] = "请先选择一个配置",
                ["GlossaryMergeResult"] = "合并完成: 新增 {0} 个术语, 更新 {1} 个",
                ["GlossaryNoConflicts"] = "未检测到术语冲突。所有翻译与术语表一致！",
                ["GlossaryConflictsTitle"] = "术语冲突",
                ["GlossaryConflictCount"] = "检测到 {0} 个术语冲突",
                ["GlossaryExpectedTranslation"] = "期望译文",
                ["GlossaryActualTranslation"] = "实际译文",
                ["GlossaryEntryKey"] = "条目 Key",
                ["GlossaryExportConflicts"] = "导出 CSV",
                ["GlossaryExportConflictsTitle"] = "导出冲突报告",
                ["GlossaryExportConflictsDone"] = "冲突报告已导出: {0}",
                ["GlossaryRequiredFields"] = "英文和中文字段为必填。",
                ["GlossaryCompare"] = "对比",

                // === Filter ===
                ["FilterKey"] = "筛选 Key",
                ["FilterOriginal"] = "筛选原文",
                ["FilterTranslation"] = "筛选译文",
                ["ClearFilter"] = "清除筛选",
                ["FilteredCount"] = "筛选 {0} / {1} 条",

                // === Activity Log ===
                ["RealTime"] = "实时",
                ["AutoScroll"] = "自动滚动",
                ["ClearLog"] = "清除日志",
                ["LogConflictStart"] = "🔍 冲突检测开始（共 {0} 条）...",
                ["LogConflictProgress"] = "🔍 冲突检测进度：{0}/{1} 条...",
                ["LogConflictDone"] = "✅ 冲突检测完成：发现 {0} 个冲突",

                // === Settings ===
                ["AIConfiguration"] = "AI 配置",
                ["ConfigureSettings"] = "配置你的 AI 翻译设置",
                ["APIKey"] = "API 密钥",
                ["EnterAPIKey"] = "输入你的 Google Gemini API 密钥",
                ["AIModel"] = "AI 模型",
                ["SelectModel"] = "选择一个 AI 模型（含速率限制和价格信息）",
                ["Refresh"] = "刷新",
                ["Loading"] = "加载中...",
                ["TargetLanguage"] = "目标语言",
                ["SelectTargetLanguage"] = "选择翻译目标语言",
                ["ProgramLanguage"] = "界面语言",
                ["SelectProgramLanguage"] = "选择程序界面语言",
                ["DisableThinking"] = "禁用思考模式（推荐）",
                ["DisableThinkingHelp"] = "DeepSeek V4 等模型默认启用思考模式，翻译任务无需推理，禁用可提速约 7 倍",
                ["CustomPrompt"] = "自定义提示词",
                ["CustomPromptHelp"] = "自定义 AI 翻译提示词。可用变量：{LANGUAGE}、{CONTEXT}、{TEXTS}、{EXPERT_CONTEXT}、{GLOSSARY}、{MIXED_SOURCE_NOTE}。",
                ["Reset"] = "重置",
                ["QuickTips"] = "快速提示",
                ["TipAPIKey"] = "从所选 AI 提供商平台获取 API 密钥",
                ["TipModels"] = "各提供商提供多种模型，可按需选择",
                ["TipRateLimits"] = "速率限制会根据模型自动优化",
                ["TipCache"] = "翻译缓存可降低 API 费用",
                ["TipLanguages"] = "支持 30 种目标语言翻译",
                ["SaveApply"] = "保存并应用",
                ["Cancel"] = "取消",
                ["NewProfile"] = "新建配置",
                ["EditProfile"] = "编辑: {0}",

                // === MessageBox titles ===
                ["MsgError"] = "错误",
                ["MsgSuccess"] = "成功",
                ["MsgConfirm"] = "确认",
                ["MsgWarning"] = "警告",
                ["MsgTip"] = "提示",

                // === MessageBox messages ===
                ["EnterAPIKeyFirst"] = "请输入 API 密钥",
                ["SelectModelFirst"] = "请选择一个模型",
                ["EnterProfileName"] = "请输入配置名称。",
                ["SelectEntriesFirst"] = "请先选择要翻译的条目",
                ["SearchTermEmpty"] = "搜索词不能为空",
                ["NoModelsFound"] = "未找到模型，请检查 API 密钥。",
                ["ModelsFoundSuccess"] = "找到 {0} 个模型（含速率限制信息）",
                ["ErrorFetchingModels"] = "获取模型出错: {0}",
                ["ConfigLoadError"] = "配置加载错误: {0}",
                ["ConfigSaveError"] = "配置保存错误: {0}",
                ["ErrorLoadingXml"] = "加载 XML 出错: {0}",
                ["UnsupportedXmlFormat"] = "无法识别的 XML 格式（根元素：{0}）。支持：LocalisationData / Excel 电子表格。",
                ["ErrorSavingXml"] = "保存 XML 出错: {0}",
                ["TranslationError"] = "翻译出错: {0}",
                ["ImportError"] = "导入出错: {0}",
                ["CacheSaveError"] = "缓存保存失败: {0}",

                // === Confirm dialogs ===
                ["ConfirmTranslate"] = "将翻译 {0} 个条目，可能需要一些时间。",
                ["ConfirmClearCache"] = "清除 {0} 条缓存翻译？",
                ["ConfirmClearDict"] = "清除 {0} 条对照表数据？不影响已完成的翻译。",
                ["ConfirmDeleteProfile"] = "确定要删除配置 \"{0}\" 吗？此操作不可撤销。",
                ["ConfirmBatchReplace"] = "替换完成！共修改 {0} 条译文\n\n可点击撤销按钮恢复",

                // === Operation results ===
                ["TranslationComplete"] = "翻译完成: {0} 成功, {1} 失败",
                ["TranslationStoppedResult"] = "翻译已停止: {0} 成功, {1} 失败",
                ["NoEntriesNeedTranslation"] = "没有需要翻译的条目",
                ["ImportCsvDone"] = "导入完成！\n新增: {0}\n更新: {1}\n跳过: {2}",
                ["ImportJsonDone"] = "导入完成！\n新增: {0}\n更新: {1}",
                ["BatchReplaceDone"] = "批量替换完成 - 替换 {0} 处",
                ["UndoComplete"] = "已撤销！恢复了 {0} 条译文",
                ["NothingToUndo"] = "没有可撤销的操作",
                ["ModelsFetchSuccess"] = "找到 {0} 个模型, 含费率信息的 {1} 个, 含速率限制的 {2} 个",

                // === File dialog titles ===
                ["SelectXmlFile"] = "选择 XML 本地化文件",
                ["SaveXmlFile"] = "保存 XML 本地化文件",
                ["ImportDictTitle"] = "导入翻译对照表",

                // === Input dialog labels ===
                ["BatchReplaceDialogTitle"] = "批量替换",
                ["SearchTermLabel"] = "搜索词：",
                ["ReplaceWithLabel"] = "替换为：",

                // === Log messages ===
                ["LogAutoLoad"] = "自动加载上次文件: {0}",
                ["LogStarted"] = "程序已启动",
                ["LogConfigLoaded"] = "配置已加载",
                ["LogConfigSaved"] = "配置已保存",
                ["LogCacheLoaded"] = "缓存已加载 - {0} 条",
                ["LogFileNotFound"] = "{0} 未找到",
                ["LogXmlLoaded"] = "XML 已加载 - {0} 条记录",
                ["LogTranslationMerged"] = "译文已合并 - {0}/{1} 条匹配",
                ["LogXmlSaved"] = "XML 已保存至 {0} - {1} 条记录",
                ["LogBatchCost"] = "批量翻译费用: ${0} ({1} 条, 输入: {2} 字符, 输出: {3} 字符)",
                ["LogSingleCost"] = "翻译费用: ${0} (输入: {1} 字符, 输出: {2} 字符)",
                ["LogParseError"] = "解析批量回复出错: {0}",
                ["LogRateLimit429"] = "速率限制 (HTTP 429), 等待 {0}s 后重试 {1}/{2}",
                ["LogRateLimitExhausted"] = "翻译失败 ({0} 次重试后): 速率限制",
                ["LogRetryError"] = "出错, {0}s 后重试: {1}",
                ["LogTranslationFailed"] = "翻译错误 ({0} 次重试后): {1}",
                ["LogModelInfo"] = "{0}: {1} (输入: {2}, 输出: {3} 令牌)",
                ["LogRateLimitEstimate"] = "{0} 预估速率限制: {1}/分钟, {2}/天",
                ["LogModelsFound"] = "找到 {0} 个模型, 含费率信息的 {1} 个, 含速率限制的 {2} 个",
                ["LogDeepSeekModels"] = "静态模型列表已加载: {0} 个模型",
                ["LogRateLimitReached"] = "达到速率限制 ({0}/分钟), 等待 {1}s",
                ["LogOptimalDelay"] = "{0} 最优延迟: {1}s ({2} 剩余请求/分钟)",
                ["LogGenericPricing"] = "使用 {0} 的通用定价 - 刷新模型获取准确价格",
                ["LogSettingsUpdated"] = "设置已更新 - 提供商: {0}, 模型: {1}, 语言: {2}, 专家: {3}",
                ["LogNoTranslationNeeded"] = "没有需要翻译的条目",
                ["LogBatchStart"] = "开始批量翻译: {0} 条, {1} 个批次{2}",
                ["LogBatchModel"] = "模型: {0}（已检查速率限制选项）",
                ["LogBatchCancelled"] = "翻译在批次 {0}/{1} 停止",
                ["LogBatchProgress"] = "处理批次 {0}/{1}: {2} 条",
                ["LogBatchFails"] = "失败 {0} 条: {1}",
                ["LogBatchRetryHalve"] = "批次 {0} 条失败（可能输出超限或超时），自动拆半重试…",
                ["LogBatchDone"] = "批次 {0}/{1} 完成: {2} 成功, {3} 失败 | 进度已保存",
                ["LogBatchElapsed"] = "批次 {0}/{1} 耗时 {2}s（{3} 条）",
                ["LogCacheSaved"] = "缓存已保存",
                ["LogTranslationDone"] = "{0}",
                ["LogTipHeader"] = "减少失败的小技巧:",
                ["LogTip1"] = "  - 稍等几秒后重试",
                ["LogTip2"] = "  - 减小代码中的批次大小（当前 50）",
                ["LogTip3"] = "  - 减少并发线程数",
                ["LogEfficiency"] = "翻译效率: {0}% ({1}/{2})",
                ["LogBatchEfficiency"] = "批量效率: {0} 次 API 调用替代 {1} 次 (节省 {2} 次调用)",
                ["LogRateLimitStatus"] = "速率限制状态: {0}/{1} 本分钟已用",
                ["LogTranslationCancelled"] = "翻译已取消",
                ["LogTranslationAlreadyRunning"] = "翻译已在运行中，请等待当前任务完成",
                ["LogProgressSaveError"] = "进度保存失败: {0}",
                ["LogCrashRecovery"] = "已从崩溃恢复文件恢复 {0} 条翻译",
                ["LogRecoveryError"] = "恢复进度文件出错: {0}",
                ["LogProgressDeleteError"] = "进度文件删除失败: {0}",
                ["LogCacheCleared"] = "缓存已清除",
                ["LogCsvImported"] = "CSV 对照表导入完成 - 新增 {0}, 更新 {1}",
                ["LogJsonImported"] = "JSON 对照表导入完成 - 新增 {0}, 更新 {1}",
                ["LogDictApplied"] = "对照表匹配到 {0} 条已有条目",
                ["LogDictCleared"] = "对照表已清除",
                ["LogPluginLoaded"] = "已加载插件 DLL：{0}",
                ["LogPluginLoadFailed"] = "加载插件失败 {0}：{1}",
                ["LogPluginFormatDiscovered"] = "发现格式插件：{0}（{1}）",
                ["LogPluginFormatFailed"] = "实例化格式插件失败 {0}：{1}",
                ["LogPluginPostDiscovered"] = "发现后处理插件：{0}",
                ["LogPluginPostFailed"] = "实例化后处理插件失败 {0}：{1}",
                ["LogVotingFailed"] = "⚠ 投票失败：{0}",
                ["LogCandidateGenFailed"] = "⚠ 候选生成失败：{0}",
                ["LogEvalParseFallback"] = "⚠ 批量评估解析失败，已回退为逐条评估",
                ["LogPerEntryEvalFailed"] = "⚠ 逐条评估失败（{0}）：{1}",
                ["LogEvalChunkFailed"] = "⚠ 批量评估分块失败：{0}",
                ["LogVotingParseFallback"] = "⚠ 批量投票解析失败，已回退为逐条投票",
                ["LogPerEntryVotingFailed"] = "⚠ 逐条投票失败（{0}）：{1}",
                ["LogVotingChunkFailed"] = "⚠ 批量投票分块失败：{0}",
                ["LogAgentScored"] = "🗳 {0} 评分 {1:F1}/10：{2}",
                ["LogVotingRegexFallback"] = "⚠ 批量投票解析失败，尝试正则回退",
                ["LogRateLimitedRetry"] = "速率限制 (HTTP 429)，重试 {0}/{1}，等待 {2}s",
                ["LogScoreCacheLoaded"] = "评分缓存已加载 - {0} 条",
                ["LogApiKeyEncryptFailed"] = "API 密钥加密失败：{0}",
                ["LogApiKeyPlaintextWarning"] = "警告：DPAPI 加密失败，API 密钥不会被保存到磁盘（仅本次会话可用）",
                ["LogApiKeyDecryptFailed"] = "API 密钥解密失败：{0}",
                ["LogMigratedLegacyKey"] = "已将旧的明文 API 密钥迁移为加密存储",
                ["LogMigrationFailed"] = "密钥迁移失败：{0}",
                ["LogScoreCacheWriteError"] = "评分缓存写入错误：{0}",
                ["LogScoresRestored"] = "已从缓存恢复 {0} 条评分",
                ["LogApiKeyNotSet"] = "未设置 API 密钥",
                ["LogModelNotSelected"] = "未选择模型",
                ["LogBatchReplace"] = "批量替换完成 - 替换 {0} 处",
                ["LogUndo"] = "已撤销上一步操作",
                ["LogCacheUpdated"] = "缓存已更新 - {0} 条",
                ["LogCacheWriteError"] = "缓存写入错误: {0}",
                ["LogCleared"] = "日志已清除",
                ["LogPaused"] = "翻译已暂停",
                ["LogResumed"] = "翻译已继续",
                ["LogStopped"] = "翻译已停止",
                ["LogExpertProfile"] = "专家配置: {0}",
                ["LogAutoRefreshModels"] = "正在自动刷新可用模型...",
                ["LogAutoModelsLoaded"] = "自动加载了 {0} 个模型",
                ["LogAutoModelSelected"] = "自动选择模型: {0}",
                ["LogClearedTranslation"] = "已清空 {0} 条译文",
                ["StatusStoppedResult"] = "翻译已停止: {0} 成功, {1} 失败",
                ["StatusBatchComplete"] = "批量翻译完成: {0} 成功, {1} 失败",

                // === Filter bar labels ===
                ["FilterLabel"] = "筛选",
                ["FilterKeyColumn"] = "Key",
                ["FilterOriginalColumn"] = "原文",
                ["FilterTranslationColumn"] = "译文",
                ["FilterClear"] = "清除",
                ["TotalCount"] = "共 {0} 条",

                // === Find bar ===
                ["FindLabel"] = "查找:",
                ["FindNoMatch"] = "无匹配",
                ["FindMatchCount"] = "{0} 个匹配",
                ["FindPrevious"] = "上一处",
                ["FindNext"] = "下一处",

                // === Context menu ===
                ["CtxCopyKey"] = "复制 Key",
                ["CtxCopyOriginal"] = "复制原文",
                ["CtxCopyTranslation"] = "复制译文",
                ["CtxClearTranslation"] = "清空译文",
                ["CtxTranslateSelected"] = "翻译选中项",
                ["CtxEvaluate"] = "AI 评估",
                ["CtxVote"] = "代理投票",
                ["CtxSelectAll"] = "全选",
                ["CtxSelectNone"] = "全不选",
                ["CtxInvertSelection"] = "反选",
                ["SelectingColumn"] = "正在选中整列",
                ["SelectingAll"] = "正在全选",
                ["InvertingSelection"] = "正在反选",
                ["SelectedCount"] = "已选中",

                // === Prompt messages ===
                ["MsgPrompt"] = "提示",
                ["SelectFirstToTranslate"] = "请先选择要翻译的条目",
                ["EnterApiKeyFirstMsg"] = "请先输入 API 密钥",

                // === Stats dialog ===
                ["StatsTitle"] = "统计",
                ["StatsInfo"] = "总条目: {0}\n已翻译: {1}\n未翻译: {2}\n进度: {3:F1}%\n\n对照表: {4} 词条 | 命中: {5}\n缓存: {6} | 命中: {7}\nAPI 调用: {8}",

                // === ToolTips ===
                ["TipSaveAs"] = "另存为...",
                ["TipQuickSave"] = "快速保存 (Ctrl+S) - 保存到当前打开的文件",
                ["TipImportDict"] = "导入 CSV/JSON 对照表",
                ["TipBatchReplace"] = "批量搜索替换译文内容",
                ["TipUndo"] = "撤销上一次批量替换",
                ["TipFilterKey"] = "筛选 Key（如 TEXT_TOOLTIP_...）",
                ["TipFilterOriginal"] = "筛选原文",
                ["TipFilterTranslation"] = "筛选译文",

                // === Dialogs ===
                ["OK"] = "确定",
                ["FileTypeTitle"] = "选择文件类型",
                ["FileTypePrompt"] = "这个文件是原文还是译文？",
                ["SourceFile"] = "原文",
                ["TranslationFile"] = "译文",

                // === Settings window ===
                ["SettingsSubtitle"] = "配置 AI 翻译和专家配置",
                ["GeneralSettings"] = "常规设置",
                ["ExpertProfiles"] = "专家配置",
                ["AiProviderLabel"] = "AI 提供商",
                ["SelectAiProvider"] = "选择 AI 翻译服务提供商",
                ["EnterYourApiKey"] = "输入你的 API 密钥",
                ["SavedProfiles"] = "已保存的配置",
                ["AddProfile"] = "新建配置",
                ["ProfileEditTitle"] = "编辑配置",
                ["ProfileNameLabel"] = "配置名称",
                ["ProfileDescLabel"] = "描述",
                ["ProfileContextLabel"] = "上下文 & 思考指令",
                ["ProfileContextHelp"] = "告诉 AI 如何理解这个领域。可以用 {LANGUAGE} 指代目标语言。",
                ["ProfileGlossaryLabel"] = "术语对照表",
                ["ProfileGlossaryHelp"] = "每行一条。格式：英文术语 = 目标翻译（例如：Jedi = 绝地）",
                ["SaveProfileBtn"] = "保存",
                ["ExpertSystemTitle"] = "专家配置系统",
                ["ExpertSystemDesc"] = "专家配置让你可以为 AI 翻译器定义特定领域的知识。每个配置包含思考指令和术语对照表。激活后，这些知识会自动注入每次翻译请求，确保专有名词和领域术语的翻译准确性。",
                ["BatchLabel"] = "批次",
                ["AppName"] = "次元译桥",

                // === Custom prompt help ===
                ["CustomPromptSyntaxHelp"] = "自定义 AI 翻译提示词。可用变量：{LANGUAGE}（目标语言）、{CONTEXT}（内容类型）、{TEXTS}（待翻译数据）、{EXPERT_CONTEXT}（专家配置知识，自动替换）、{GLOSSARY}（术语对照表，自动注入）、{MIXED_SOURCE_NOTE}（混合批次修正指令）。",

                // === Quick tips ===
                ["QuickTipsTitle"] = "快速提示",
                ["QuickTipsContent"] = "• 支持 8 个主流 AI 提供商（Google/DeepSeek/豆包/千问/智谱/Kimi/文心/讯飞）\n• 各提供商提供多种模型，可按需选择\n• 批量翻译自动并发处理，提升效率\n• 术语对照表自动注入，确保翻译一致性\n• 翻译缓存降低 API 费用\n• AI 评估与多代理投票提升翻译质量\n• 支持 30 种目标语言翻译\n• 专家配置可注入领域知识，增强专业翻译",

                // === Misc labels ===
                ["CostLabel"] = "费用",
                ["LoadModelRefreshHint"] = "（点击刷新加载完整列表）",

                // === AI Evaluation & Voting ===
                ["EvaluateBtn"] = "AI 评估",
                ["VoteBtn"] = "代理投票",
                ["EvaluateToolTip"] = "AI 翻译质量评估（0-10 评分）",
                ["VoteToolTip"] = "多代理投票选出最佳译文",
                ["EvalEvaluating"] = "评估中...",
                ["EvalVoting"] = "投票中...",
                ["EvalFailed"] = "评估失败",
                ["VoteFailed"] = "投票失败",
                ["Best"] = "最佳",
                ["NoTranslatedToEvaluate"] = "没有已翻译的条目可评估",
                ["NoTranslatedToVote"] = "没有已翻译的条目可投票",
                ["LogEvaluating"] = "正在评估: {0}",
                ["LogVoting"] = "代理投票: {0}",
                ["LogEvalResult"] = "{0}: {1:F1}/10 — {2}",
                ["LogEvalSuggestion"] = "改进建议: {0}",
                ["LogVoteConsensus"] = "{0}",
                ["LogVoteAgentDetail"] = "  {0}: {1:F1}/10 — {2}",
                ["EvalScoreToolTip"] = "评分: {0:F1}/10\n解释: {1}\n建议: {2}",
                ["VoteResultToolTip"] = "平均分: {0:F1}/10\n共识: {1}\n投票数: {2}",

                // === Target language names ===
                ["Lang_Turkish"] = "土耳其语",
                ["Lang_Spanish"] = "西班牙语",
                ["Lang_French"] = "法语",
                ["Lang_German"] = "德语",
                ["Lang_Italian"] = "意大利语",
                ["Lang_Portuguese"] = "葡萄牙语",
                ["Lang_Russian"] = "俄语",
                ["Lang_Japanese"] = "日语",
                ["Lang_Korean"] = "韩语",
                ["Lang_Chinese_Simplified"] = "简体中文",
                ["Lang_Chinese_Traditional"] = "繁体中文",
                ["Lang_Arabic"] = "阿拉伯语",
                ["Lang_Hindi"] = "印地语",
                ["Lang_Dutch"] = "荷兰语",
                ["Lang_Swedish"] = "瑞典语",
                ["Lang_Norwegian"] = "挪威语",
                ["Lang_Danish"] = "丹麦语",
                ["Lang_Finnish"] = "芬兰语",
                ["Lang_Polish"] = "波兰语",
                ["Lang_Czech"] = "捷克语",
                ["Lang_Hungarian"] = "匈牙利语",
                ["Lang_Romanian"] = "罗马尼亚语",
                ["Lang_Greek"] = "希腊语",
                ["Lang_Bulgarian"] = "保加利亚语",
                ["Lang_Ukrainian"] = "乌克兰语",
                ["Lang_Thai"] = "泰语",
                ["Lang_Vietnamese"] = "越南语",
                ["Lang_Indonesian"] = "印尼语",
                ["Lang_Hebrew"] = "希伯来语",
                ["Lang_Persian"] = "波斯语",

                // === Review & Export ===
                ["ExportReview"] = "导出审校报告",
                ["ReviewReport"] = "审校报告",
                ["ReviewStatusReviewed"] = "已审校",
                ["ReviewStatusNeedsFix"] = "需修改",
                ["ReviewStatusNotReviewed"] = "未审校",
                ["MarkedEntriesAsStatus"] = "已将 {0} 条标记为 {1}",
                ["ExportReviewLog"] = "审校报告已导出: {0} 条 | ✅ {1} | 🔧 {2} | 📝 {3}",
                ["ExportReviewMsg"] = "已导出 {0} 条。\n已审校: {1}\n需修改: {2}\n未审校: {3}",

                // === Evaluation Window ===
                ["EvaluationTitle"] = "翻译质量评估",
                ["EvalScoreDist"] = "评分分布: ",
                ["EvalHighCount"] = "优秀 (8-10): {0}",
                ["EvalMidCount"] = "良好 (5-7): {0}",
                ["EvalLowCount"] = "较差 (0-4): {0}",
                ["EvalAvgScore"] = "平均分: {0:F1}/10",
                ["EvalEvaluated"] = "已评估 {0} 条",
                ["EvalNA"] = "N/A",
                ["EvalApplySuggestion"] = "应用建议",
                ["EvalMarkLowScores"] = "标记低分条目",
                ["EvalClose"] = "关闭",
                ["EvalMarkComplete"] = "标记完成",
                ["EvalMarkedEntries"] = "已标记 {0} 条待审校。",
                ["EvalAppliedSuggestion"] = "已应用建议: {0}",
                ["EvalMarkAsLow"] = "标记为低分: {0} (评分: {1:F1})",

                // === Batch Evaluation & Voting ===
                ["LogBatchEvaluating"] = "正在评估 {0} 条翻译...",
                ["EvalBatchProgress"] = "评估中 {0}...",
                ["EvalNoResults"] = "无结果",
                ["EvalBatchSummary"] = "平均: {0:F1} | 优秀: {1} | 较差: {2}",
                ["LogBatchEvalComplete"] = "批量评估完成: {0} 条, 平均: {1:F1}, 优秀: {2}, 较差: {3}",
                ["LogScoreUpdated"] = "已更新 {0} 条评分到表格（点击「评分」列头可排序）",
                ["LogBatchVoting"] = "多代理投票中 {0} 条...",
                ["VoteBatchProgress"] = "投票中 {0}...",
                ["VoteBatchResult"] = "{0} 条已投票 | 最优: {1}",
                ["LogBatchVoteComplete"] = "批量投票完成: {0} 条, {1} 条评为最优",
                ["LogAppliedSuggestion"] = "已应用建议: {0}",
                ["VoteAppliedBest"] = "投票完成: 已为 {0} 条应用最佳译文",
                ["LogGeneratingCandidate"] = "生成候选译文 [{0}/{1}]: {2}",
                ["VoteCandidateProgress"] = "生成候选译文 [{0}/{1}]...",
                ["LogVotingStart"] = "开始多代理投票 {0} 条...",
                ["VoteVotingProgress"] = "投票中 {0} 条...",
                ["VoteBatchResultDetail"] = "{0} 条已投票 | 最优: {1} | 待确认: {2}",
                ["VoteBestTranslation"] = "最佳译文",
                ["VoteApplyPrompt"] = "是否将 \"{0}\" 的最佳译文应用？\n\n{1}",
                ["VoteApplyTitle"] = "应用最佳译文",
                ["VoteApplied"] = "已为 {0} 应用最佳译文",
                ["VoteNeedsReview"] = "{0} 条需要人工确认",
                ["VotingReviewTitle"] = "投票候选确认",
                ["VotingReviewHint"] = "{0} 条需要人工确认，请为每条选择要使用的译文",
                ["VotingKeepCurrent"] = "（保持当前译文）",
                ["VotingCandidateFormat"] = "候选 {0}（均分 {1:F1}/10）",
                ["VotingApplySelected"] = "应用所选",
                ["VotingCancel"] = "取消",

                // === Glossary ===
                ["GlossaryShare"] = "分享",
                ["GlossaryShareTitle"] = "分享术语表给社区",
                ["GlossaryShareResult"] = "已分享 {0} 条术语供社区使用。",
                ["GlossaryImportTitle"] = "导入术语表",
                ["GlossaryExportTitle"] = "导出术语表",
                ["MsgError"] = "错误",

                // === File dialog ===
                ["FileFilterAllSupported"] = "所有支持的文件",
                ["FileFilterXml"] = "XML 文件",
                ["FileFilterPo"] = "PO 文件",
                ["FileFilterJson"] = "JSON 文件",
                ["FileFilterAll"] = "所有文件",
                ["FileFilterCsv"] = "CSV 文件",

                // === Save/Load with plugins ===
                ["LogSavedFile"] = "已保存 {0} 条 ({1}): {2}",
                ["LogLoadedFile"] = "已加载 {0} 条 ({1}): {2}",
                ["StatusSavedPlugin"] = "已保存 {0} 条 ({1})",

                // === Term Edit Dialog ===
                ["TermAddTitle"] = "新增术语",
                ["TermEditTitle"] = "编辑术语",

                // === Misc dialogs ===
                ["GlossaryShareResultTitle"] = "已分享",
                ["ExportFailed"] = "导出失败: {0}",

                // === Progress display ===
                ["ProgressDisplay"] = "{0:F1}% ({1}/{2})",
                ["SpeedDisplay"] = "{0:F1}/s",
                ["EtaDisplay"] = "{0}",
                ["CostDisplay"] = "${0:F4}",
                ["FindPosition"] = "{0} / {1}",
                ["LogFileClosed"] = "文件已关闭",
                ["NoFileLoaded"] = "未加载文件",

                // === Menu ===
                ["MenuFile"] = "文件",
                ["MenuEdit"] = "编辑",
                ["MenuView"] = "视图",
                ["MenuTranslate"] = "翻译",
                ["MenuQuality"] = "质量",
                ["MenuTools"] = "工具",
                ["MenuHelp"] = "帮助",
                ["MenuOpen"] = "打开...",
                ["MenuSave"] = "保存",
                ["MenuSaveAs"] = "另存为...",
                ["MenuExport"] = "导出",
                ["MenuExit"] = "退出",
                ["MenuUndo"] = "撤销",
                ["MenuFind"] = "查找...",
                ["MenuReplace"] = "替换...",
                ["MenuDarkMode"] = "暗色模式",
                ["MenuLightMode"] = "亮色模式",
                ["MenuShowFilter"] = "显示筛选栏",
                ["MenuShowLog"] = "显示日志面板",
                ["MenuSmartPre"] = "智能预翻译",
                ["MenuConsistency"] = "一致性扫描",
                ["MenuShortcuts"] = "键盘快捷键",
                ["MenuAbout"] = "关于",

                // === Untranslated filter ===
                ["ShowUntranslatedOnly"] = "仅显示未翻译",
                ["ShowAll"] = "显示全部",
                ["HideBlacklisted"] = "隐藏黑名单",

                // === Smart Pre-translate ===
                ["PreTranslate"] = "智能预翻译",
                ["PreTranslateTip"] = "使用术语表和缓存填充译文，无需 API 调用",
                ["PreTranslateResult"] = "{0} 条预翻译完成（术语表: {1}, 缓存: {2}）",
                ["LogPreTranslate"] = "智能预翻译: 填充 {0} 条（术语表: {1}, 缓存: {2}）",

                // === Consistency Scan ===
                ["ConsistencyScan"] = "一致性扫描",
                ["ConsistencyScanTitle"] = "一致性检查结果",
                ["ConsistencyScanning"] = "正在扫描一致性问题...",
                ["ConsistencyNoIssues"] = "未发现一致性问题。",
                ["ConsistencyIssueDesc"] = "{0} → 分别译为 \"{1}\" 和 \"{2}\"",
                ["LogConsistencyScan"] = "一致性扫描: 在 {1} 条中发现 {0} 个问题",
                ["ConsistencyExportPrompt"] = "发现 {0} 个一致性问题，是否导出报告以便对照修改？",
                ["ConsistencyExported"] = "一致性报告已导出: {0}",

                // === Context-aware Translation ===
                ["ContextAware"] = "上下文感知",
                ["LogContextAware"] = "上下文感知模式: 正在分析 {1} 的 {0} 条相邻条目",

                // === Fuzzy Matching ===
                ["FuzzyMatch"] = "模糊匹配",
                ["FuzzyMatchResult"] = "为 \"{1}\" 找到 {0} 个模糊匹配",

                // === Multi-file ===
                ["ProjectFiles"] = "项目文件",
                ["CloseFile"] = "关闭文件",
                ["CloseTab"] = "关闭",

                // === About ===
                ["AboutTitle"] = "关于次元译桥",
                ["AboutText"] = "次元译桥 v1.0\n\nAI 驱动的游戏本地化工具。\n支持 XML、CSV、JSON、INI、YAML、RESX、PO、TXT、Android 格式。\n\n8 种 AI 提供商，30+ 种语言。",

                // === Shortcuts ===
                ["ShortcutsTitle"] = "键盘快捷键",
                ["ShortcutsText"] = "Ctrl+O   打开文件\nCtrl+S   快速保存\nCtrl+Z   撤销\nCtrl+F   查找\nF5       AI 评估\nF6       代理投票\nCtrl+T   翻译选中\nCtrl+Shift+T  全部翻译\nEscape   清除筛选",

                // === 评估模型设置 ===
                ["EvalModelTab"] = "评估模型",
                ["EvalModelConfig"] = "评估模型配置",
                ["EvalModelDesc"] = "配置独立的 AI 模型用于翻译评估和投票，打破同源偏差。留空则使用翻译模型进行评估。",
                ["EvalAiProviderLabel"] = "评估 AI 提供商",
                ["EvalApiKeyLabel"] = "评估 API 密钥",
                ["EvalApiKeyPlaceholder"] = "输入评估模型的 API 密钥（留空则使用翻译密钥）",
                ["EvalModelNameLabel"] = "评估模型名称",
                ["EvalModelPlaceholder"] = "输入模型名称，如 deepseek-chat、glm-4-flash",
                ["EvalUseTranslationModel"] = "（使用翻译模型）",
                ["EvalRefreshModels"] = "刷新模型",
                ["EvalAddModel"] = "添加模型",
                ["EvalAddedModels"] = "已配置的评估模型",
                ["EvalModelListEmpty"] = "（未添加模型——投票将使用翻译模型）",
                ["EvalSelectModelFirst"] = "请先选择模型",
                ["EvalModelAdded"] = "已添加模型：{0}",
                ["EvalUseSameKeyHint"] = "同一厂商的模型可共用同一 API 密钥；投票将依次调用所有已配置的模型。",
            };
        }
    }
}
