using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using SimpleXmlEditor.Services;

namespace SimpleXmlEditor.Plugins
{
    /// <summary>
    /// Supports GNU Gettext .po / .pot file format for translation.
    /// Format: msgid "original" / msgstr "translation"
    /// </summary>
    public class PoFilePlugin : IFileFormatPlugin
    {
        public string FormatName => "GNU Gettext (PO/POT)";
        public string[] FileExtensions => new[] { ".po", ".pot" };

        private static readonly Regex MsgidRegex = new Regex(@"^msgid\s+""(.*)""\s*$", RegexOptions.Compiled);
        private static readonly Regex MsgstrRegex = new Regex(@"^msgstr\s+""(.*)""\s*$", RegexOptions.Compiled);

        public List<LocalizationEntry> Load(string filePath)
        {
            var entries = new List<LocalizationEntry>();
            var lines = File.ReadAllLines(filePath, Encoding.UTF8);

            string currentMsgId = null;
            var mbMsgId = new List<string>();
            var mbMsgStr = new List<string>();
            bool inMsgId = false, inMsgStr = false;
            int index = 0;

            foreach (var line in lines)
            {
                var trimmed = line.Trim();

                // Skip comments and empty lines
                if (string.IsNullOrEmpty(trimmed) || trimmed.StartsWith("#"))
                {
                    if (currentMsgId != null && (mbMsgId.Count > 0 || mbMsgStr.Count > 0))
                    {
                        FlushEntry(entries, ref index, currentMsgId, mbMsgId, mbMsgStr);
                        currentMsgId = null;
                    }
                    continue;
                }

                // Multi-line continuation
                if (trimmed.StartsWith("\"") && trimmed.EndsWith("\""))
                {
                    var text = Unescape(trimmed[1..^1]);
                    if (inMsgId) mbMsgId.Add(text);
                    else if (inMsgStr) mbMsgStr.Add(text);
                    continue;
                }

                // msgid
                if (trimmed.StartsWith("msgid "))
                {
                    if (currentMsgId != null)
                    {
                        FlushEntry(entries, ref index, currentMsgId, mbMsgId, mbMsgStr);
                    }
                    inMsgId = true;
                    inMsgStr = false;
                    mbMsgId.Clear();
                    mbMsgStr.Clear();

                    var match = MsgidRegex.Match(trimmed);
                    if (match.Success)
                    {
                        currentMsgId = Unescape(match.Groups[1].Value);
                        if (!string.IsNullOrEmpty(currentMsgId))
                            mbMsgId.Add(currentMsgId);
                    }
                    else
                    {
                        currentMsgId = "";
                    }
                    continue;
                }

                // msgstr
                if (trimmed.StartsWith("msgstr "))
                {
                    inMsgId = false;
                    inMsgStr = true;
                    var match = MsgstrRegex.Match(trimmed);
                    if (match.Success)
                    {
                        mbMsgStr.Add(Unescape(match.Groups[1].Value));
                    }
                    continue;
                }
            }

            // Flush last entry
            if (currentMsgId != null)
                FlushEntry(entries, ref index, currentMsgId, mbMsgId, mbMsgStr);

            return entries;
        }

        private void FlushEntry(List<LocalizationEntry> entries, ref int index, string msgId,
            List<string> msgIdLines, List<string> msgStrLines)
        {
            var key = string.Join("", msgIdLines.Count > 0 ? msgIdLines : new[] { msgId });
            if (string.IsNullOrEmpty(key)) return;

            var translation = string.Join("", msgStrLines);
            index++;
            entries.Add(new LocalizationEntry
            {
                RowNumber = index,
                Key = key.Length > 60 ? key[..60] : key,
                Value = key,
                Translation = translation
            });
        }

        public void Save(string filePath, List<LocalizationEntry> entries)
        {
            var sb = new StringBuilder();
            sb.AppendLine("# Generated by XML AI Translator");
            sb.AppendLine("#, fuzzy");
            sb.AppendLine("msgid \"\"");
            sb.AppendLine("msgstr \"\"");
            sb.AppendLine("\"Content-Type: text/plain; charset=UTF-8\\n\"");
            sb.AppendLine();

            foreach (var entry in entries)
            {
                if (string.IsNullOrEmpty(entry.Value)) continue;

                sb.AppendLine($"msgid \"{Escape(entry.Value)}\"");
                sb.AppendLine($"msgstr \"{Escape(entry.Translation ?? "")}\"");
                sb.AppendLine();
            }

            File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);
        }

        private static string Escape(string text)
        {
            return text.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r");
        }

        private static string Unescape(string text)
        {
            return text.Replace("\\\"", "\"").Replace("\\n", "\n").Replace("\\r", "\r").Replace("\\\\", "\\");
        }
    }
}
